# Generated by Django 6.0.2 on 2026-03-18 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_session_context_max'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_id', models.CharField(max_length=100, unique=True)),
                ('cron_expr', models.CharField(max_length=100)),
                ('recurring', models.BooleanField()),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('next_fire', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crons', to='core.session')),
            ],
            options={
                'indexes': [models.Index(fields=['session'], name='idx_sessioncron_session')],
            },
        ),
    ]
